AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  auth.nikxy.dev - Testing

  SAM Template for auth.nikxy.dev testing

Globals:
  Function:
    Timeout: 10

Resources:
  LoginFunction:
    FunctionName: LoginFunction
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          REGION: eu-central-1
          DB_TABLE: nikxy-auth
          JWT_SECRET: "nikxy/auth/jwtsecrets"
          LOCAL_ENDPOINT: "http://localstack.dev.callandorit.net"
      Events:
        LoginOptions:
          Type: Api
          Properties:
            Path: /login
            Method: options
        Login:
          Type: Api
          Properties:
            Path: /login
            Method: post
        RefreshOptions:
          Type: Api
          Properties:
            Path: /refresh
            Method: options
        Refresh:
          Type: Api
          Properties:
            Path: /refresh
            Method: get
        StatusOptions:
          Type: Api
          Properties:
            Path: /status
            Method: options
        Status:
          Type: Api
          Properties:
            Path: /status
            Method: get
        LogoutOptions:
          Type: Api
          Properties:
            Path: /logout
            Method: options
        Logout:
          Type: Api
          Properties:
            Path: /logout
            Method: get