def PROJECT_FOLDER = 'lambda-login'

pipeline {
    agent any
    
    tools { nodejs 'Node 18.x' }

    environment {
        REGION = 'eu-central-1'
    }

    stages {
        stage('Clone Source') {
            steps {
                git branch: 'master',
                url: 'https://c16adb70562dc0fcfb69f83802bafb4044b3ef4e@gogs.dev.callandorit.net/nikxy/lambda-auth.git'
            }
        }
        stage('Install dependencies') {
            when {
                changeset 'lambda-login/package.json'
            }

            steps {
                dir(PROJECT_FOLDER) {
                    sh 'npm install'
                }
            }
        }
        stage('Unit Tests') {
            /*environment { // Should'nt be used in unit tests, only integration
                LOCAL_ENDPOINT = 'http://localstack_main:4566'

                DB_TABLE = 'nikxy-auth'
                JWT_SECRET_KEY = 'nikxy/auth/jwtsecrets'
            }*/
            steps {
                dir(PROJECT_FOLDER) {
                    sh 'npm run test_ci'
                }
            }
            post {
                always {
                    dir(PROJECT_FOLDER) {
                        junit 'output/coverage/junit/junit.xml'
                    }
                }
            }
        }
        stage('Deploy To AWS') {
            steps {
                dir(PROJECT_FOLDER) {
                    sh 'zip -FSr deploymentFile.zip . -x ./jest.config.mjs ./__tests__/**\\* ./__tests__/ ./node_modules/@aws-sdk/**\\* ./node_modules/@aws-sdk/'
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'AWSJenkinsDeploy',
                            usernameVariable: 'accessKeyId',
                            passwordVariable: 'accessKeySecret'
                        )]) {
                        sh 'echo $accessKeyId'
                        deployLambda([
                            alias: '',
                            artifactLocation: 'deploymentFile.zip',
                            awsAccessKeyId: accessKeyId,
                            awsRegion: "${REGION}",
                            awsSecretKey: accessKeySecret,
                            deadLetterQueueArn: '',
                            description: '',
                            environmentConfiguration: [kmsArn: ''],
                            functionName: 'nikxy-auth-login',
                            handler: '', memorySize: '',
                            role: '', runtime: '',
                            securityGroups: '', subnets: '', timeout: '',
                            updateMode: 'code'
                        ])
                        }
                    sh 'rm deploymentFile.zip'
                }
            }
        }
    }
}
